#!/usr/bin/env guile
!#

(use-modules (figl parse)
             (ice-9 pretty-print))

(setlocale LC_ALL "")

(print-disable 'escape-newlines)

(fold-gl-definitions
 (lambda (name prototype docstring)
   (pretty-print
    `(define-gl-procedure ,(string->symbol name) ,name ,prototype
       ,docstring))
   (newline)
   (values))
 2)
